name: tutorial_flutter_navigation_v2
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BSD
  # Android, IOS, Linux, macOS, WEB, Windows
  cupertino_icons: ^1.0.2

  # MIT
  # Android, IOS, Linux, macOS, WEB, Windows
  equatable: ^2.0.0
  universal_html: ^2.0.8
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true